### ISSUE TITLE
"Debug as" -> Web Application (Dev or Superdev) gives error.

### ISSUE THREAD

**Issue by slavap** [gwt-eclipse-plugin/gwt-eclipse-plugin#59] opened 2015-05-12 00:49 UTC
Error: Could not find any host pages in project myProject1.

I can add debug configuration manually, then it works just fine.

Another strange thing that main class is substituted as com.google.gwt.dev.GWTShell, though it should be com.google.gwt.dev.DevMode

**Comment by branflake2267** [comment] 2015-05-12 00:56
Thanks for reporting and testing. Could you provide the steps you used to produce that or what are the steps I could do to replicate that?

**Comment by branflake2267** [comment] 2015-05-12 00:57
Could you provide the project that I could use as a test case?

**Comment by slavap** [comment] 2015-05-12 01:46
It's not easy, because my current projects are not open source :-(
But I've found the one, which can be used to reproduce this problem.

1. I'm using the latest Eclipse STS 3.6.4 (just FYI, don't think it's so important).
2. Clone git: https://github.com/nippur72/Dart.RayTracerDemo.git
3. Import project to Eclipse (you can safely edit 2.6.1 to 2.7.0 in pom.xml)
4. GWT Compile.
5. Right click on javaraytracerdemo -> Debug As -> Web Application (any choice Dev or Superdev)
6. Error: Could not find any host pages in project myProject1.

To workaround the problem:
7. Debug Configuration -> Web Application (right click) -> New
8. Main class is substituted as com.google.gwt.dev.GWTShell, fix it as com.google.gwt.dev.DevMode
9. Also manually add to debug configuration -> Arguments the following: -startupUrl gwt_raytracerdemo.html

Now you able to run this project.

**Comment by branflake2267** [comment] 2015-05-12 15:08
Thank you for working on that. I'll take a look and see if I can squash soon.

**Comment by slavap** [comment] 2015-05-12 19:48
Thank you for taking care of GPE plugin, it was kind of slow maintained before you, so I'm really happy someone started to pay attention to it, it's very important part of GWT.

**Comment by branflake2267** [comment] 2015-05-19 04:01
There are two issues here. 
1. The pom.xml gwt-maven-plugin is missing the <module/> definition. 
2. The module is in src/main/resources which is also issue 66, where something is not adding this to the classpath.

**Comment by branflake2267** [comment] 2015-05-19 04:04
M2e default configuration for resources directory is to exclude it from the classpath, which creates a problem when the compiler is activated. 

![screen shot 2015-05-18 at 9 03 24 pm](https://cloud.githubusercontent.com/assets/1326504/7695246/618f3086-fda1-11e4-9000-4c9cc741acab.png)

**Comment by branflake2267** [comment] 2015-05-19 04:05
I'm going to close this bug as duplicate of Issue 66.

https://github.com/gwt-eclipse-plugin/gwt-eclipse-plugin/issues/66

**Closed by branflake2267** 2015-05-19 04:05 UTC
Labels: bug
